<script>
    let name = 'Svelte';
    let src = 'https://picsum.photos/200';
    let alt = 'random gen pic';
    let string = 'this string contains some <strong>HTML!!!</strong>';
    
    import Nested from './nested.svelte'
</script>

<h1>Hello {name.toLocaleUpperCase()}</h1>

<img src={src} alt="A random pic generated by picsum">
<!-- todo OR use horthand attribute -->
<img {src} {alt} >

<p>This is some text, <b>scopeley styled</b></p>

<!-- Add another paragraph, which styles do not get affected by the scoped styling -->
<Nested />

<!-- Add '@html' to render html directly into component -->
<p>{@html string}</p>


<style>
    p {
        color: goldenrod;
        font-family: 'Comic Sans MS', cursive;
        font-size: 2em;
    }
</style>